version: '3'

services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - 8083:8083
            - 8086:8086
        volumes:
            - influxdb-volume:/var/lib/influxdb
        # environment:
        #     - INFLUXDB_DB=db0
        #     - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
        #     - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

    mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mosquitto
        ports:
            - 1883:1883
        volumes:
            # - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
            - mosquitto-volume:/var/lib/mosquitto

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            - grafana-volume:/var/lib/grafana
        depends_on:
            - influxdb
            - mosquitto
        # environment:
        #     - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
        #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

    chronograf:
        image: chronograf:latest
        container_name: chronograf
        ports:
            - 8888:8888
        volumes:
            - chronograf-volume:/var/lib/chronograf
        depends_on:
            - influxdb
            - mosquitto
        # environment:
        #   - INFLUXDB_URL=http://influxdb:8086
        #   - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
        #   - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
volumes:
    influxdb-volume:
    mosquitto-volume:
    grafana-volume:
    chronograf-volume:
