version: '3'

services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - 8083:8083
            - 8086:8086
        volumes:
            # - ./influxdb-volume/config:/etc/influxdb/influxdb.conf
            - ./influxdb-volume:/var/lib/influxdb
        # environment:
        #     - INFLUXDB_DB=db0
        #     - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
        #     - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

    # chronograf:
    #     image: chronograf:latest
    #     container_name: chronograf
    #     ports:
    #         - 8888:8888
    #     volumes:
    #         - ./chronograf-volume:/var/lib/chronograf
    #     depends_on:
    #         - influxdb
    #         - kapacitor
    #         - telegraf
    #     links:
    #         - influxdb
    #         - kapacitor
    #     environment:
    #       - INFLUXDB_URL=http://influxdb:8086
    #       - KAPACITOR_URL=http://kapacitor:9092
    #     #   - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
    #     #   - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}

    kapacitor:
        image: kapacitor:latest
        container_name: kapacitor
        ports:
            - 9092:9092
        volumes:
            # - ./kapacitor-volume/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf
            - ./kapacitor-volume:/var/lib/kapacitor
        depends_on:
            - influxdb
        links:
            - influxdb
        environment:
            - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
        #     - INFLUXDB_URL=http://influxdb:8086
        #     - VIRTUAL_HOST=${KAPACITOR_HOST}
        #     - VIRTUAL_PORT=9092
        #     - LETSENCRYPT_HOST=${KAPACITOR_HOST}
        #     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}

    # telegraf:
    #     image: telegraf:latest
    #     container_name: telegraf
    #     command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    #     # ports:
    #     #     -
    #     volumes:
    #         - ./telegraf-volume/config/telegraf.conf:/etc/telegraf/telegraf.conf
    #         - ./telegraf-volume/config/telegraf.d:/etc/telegraf/telegraf.d
    #     depends_on:
    #         - influxdb
    #     links:
    #         - influxdb

    mosquitto:
        image: eclipse-mosquitto:latest
        container_name: mosquitto
        ports:
            - 1883:1883
        volumes:
            # - ./mosquitto-volume/config/mosquitto.conf:/etc/mosquitto/mosquitto.conf
            - ./mosquitto-volume:/var/lib/mosquitto
        depends_on:
            - influxdb
        links:
            - influxdb

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - 3000:3000
        volumes:
            # - ./grafana-volume/config/grafana.conf:/etc/grafana/grafana.conf
            - ./grafana-volume:/var/lib/grafana
        depends_on:
            - influxdb
        # environment:
        #     - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
        #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}

volumes:
    influxdb-volume:
    # chronograf-volume:
    kapacitor-volume:
    # telegraf-volume:
    mosquitto-volume:
    grafana-volume:
